describe('links test', () => {
    beforeEach(() => {
      cy.visit('/en/users/sign_in')
    })
    it('left side menu links test', () => {
        cy.get('.page-title--h1').should('contain.text', 'Log in to your ZenHR account')
        cy.get('#user_login').type('tillawy@hotmail.com')
        cy.get('#user_password').type('password')
        cy.get('button[type="submit"]').click()
        cy.get('#flash_notice').should('exist')
        cy.get('#flash_notice').should('contain.text','Signed in successfully.')
        cy.get('span[class="am-toggle-left-sidebar__icon-bar"]').then($sidemenutoggle => {
          if($sidemenutoggle.is(':visible')) {
            console.log('the toggle is visible')
            cy.get($sidemenutoggle).click()
          }
        })
        cy.pathDataTest('Employees').click()
    
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/employees/directory"]').click()
          cy.location("pathname").should("equal","/en/employees/directory")
        })
    
        cy.openSideMenu().click()
        cy.pathDataTest('Employees').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/employees"]').contains('Employee Management').click()
          cy.location("pathname").should("equal","/en/employees")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Employees').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/mass_change_transactions"]').contains('Mass Actions').click()
          cy.location("pathname").should("equal","/en/mass_change_transactions")
        })
        cy.openSideMenu().click()
        cy.get('[data-dismiss="modal"]').contains('Close').click()
        cy.pathDataTest('Employees').click()
        
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/employees/org_structure"]').contains('Employees Hierarchy').click()
          cy.location("pathname").should("equal","/en/employees/org_structure")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Employees').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/boardings"]').contains('Onboarding and Offboarding').click()
          cy.location("pathname").should("equal","/en/boardings")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Employees').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/pending_employees"]').contains('Pending Employees').click()
          cy.location("pathname").should("equal","/en/pending_employees")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Employees').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/task/requests"]').contains('My Tasks').click()
          cy.location("pathname").should("equal","/en/task/requests")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Employees').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/tasks"]').contains('Manage Tasks').click()
          cy.location("pathname").should("equal","/en/tasks")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Employees').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/disciplinary_actions"]').contains('Manage Disciplinary Actions').click()
          cy.location("pathname").should("equal","/en/disciplinary_actions")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Time Management').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/timeoff_transactions"]').contains('Manage Time Offs').click()
          cy.location("pathname").should("equal","/en/timeoff_transactions")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Time Management').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/timeoff_transaction/adjustments"]').contains('Manage Adjustments').click()
          cy.location("pathname").should("equal","/en/timeoff_transaction/adjustments")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Time Management').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/timeoff_transaction/moved_balances"]').contains('Manage Moved Balances').click()
          cy.location("pathname").should("equal","/en/timeoff_transaction/moved_balances")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Time Management').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/timeoff_transaction/requests"]').contains('My Timeoff Requests').click()
          cy.location("pathname").should("equal","/en/timeoff_transaction/requests")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Time Management').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/attendance_records/personal"]').contains('Attendance History').click()
          cy.location("pathname").should("equal","/en/attendance_records/personal")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Time Management').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/missing_punches"]').contains('My Missing Punch Requests').click()
          cy.location("pathname").should("equal","/en/missing_punches")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Time Management').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/attendance_sheets/new"]').contains('Attendance Sheets').click()
          cy.location("pathname").should("equal","/en/attendance_sheets/new")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Time Management').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/employee_shifts"]').contains('Employee Shifts').click()
          cy.location("pathname").should("equal","/en/employee_shifts")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Time Management').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/attendance_records"]').contains('Manage Attendance Records').click()
          cy.location("pathname").should("equal","/en/attendance_records")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Time Management').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/old_attendance_recommendations"]').contains('Recommendations').click()
          cy.location("pathname").should("equal","/en/old_attendance_recommendations")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Time Management').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/reports/attendance_records"]').contains('Attendance Report').click()
          cy.location("pathname").should("equal","/en/reports/attendance_records")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Time Management').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/reports/attendance_details"]').contains('Attendance Details Report').click()
          cy.location("pathname").should("equal","/en/reports/attendance_details")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Time Management').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/accumulative_reports"]').contains('Accumulative Attendance Report').click()
          cy.location("pathname").should("equal","/en/accumulative_reports")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Payroll').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/financial_transaction/requests"]').contains('Financial Requests').click()
          cy.location("pathname").should("equal","/en/financial_transaction/requests")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Payroll').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/overtime/requests"]').contains('Overtime Requests').click()
          cy.location("pathname").should("equal","/en/overtime/requests")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Payroll').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/airticket_transaction/requests"]').contains('Air Ticket Requests').click()
          cy.location("pathname").should("equal","/en/airticket_transaction/requests")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Payroll').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/loan/requests"]').contains('My Loans').click()
          cy.location("pathname").should("equal","/en/loan/requests")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Payroll').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/financial_transactions"]').contains('Manage Financial Transactions').click()
          cy.location("pathname").should("equal","/en/financial_transactions")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Payroll').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/overtimes"]').contains('Manage Overtimes').click()
          cy.location("pathname").should("equal","/en/overtimes")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Payroll').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/airticket_transactions"]').contains('Manage Air Ticket Transactions').click()
          cy.location("pathname").should("equal","/en/airticket_transactions")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Payroll').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/part_time_transactions"]').contains('Manage Air Manage Part-Time Transactions Transactions').click()
          cy.location("pathname").should("equal","/en/part_time_transactions")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Payroll').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/salaries"]').contains('Manage Salaries').click()
          cy.location("pathname").should("equal","/en/salaries")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Payroll').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/in_advanced_salary_batches"]').contains('Manage Vacation In-Advance Salary').click()
          cy.location("pathname").should("equal","/en/in_advanced_salary_batches")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Payroll').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/time_sheets"]').contains('Manage Timesheets').click()
          cy.location("pathname").should("equal","/en/time_sheets")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Payroll').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/loans"]').contains('Manage Loans').click()
          cy.location("pathname").should("equal","/en/loans")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Payroll').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/expenses"]').contains('Manage expenses').click()
          cy.location("pathname").should("equal","/en/expenses")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Payroll').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/provision_histories"]').contains('Manage Monthly Provisions').click()
          cy.location("pathname").should("equal","/en/provision_histories")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Documents').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/employees/53497/documents"]').contains('My Documents').click()
          cy.location("pathname").should("equal","/en/employees/53497/documents")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Documents').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/documents/shared"]').contains('Shared Documents').click()
          cy.location("pathname").should("equal","/en/documents/shared")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Documents').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/documents"]').contains('Manage Documents').click()
          cy.location("pathname").should("equal","/en/documents")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Documents').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/employees/53497/hr_letters"]').contains('My HR Letters').click()
          cy.location("pathname").should("equal","/en/employees/53497/hr_letters")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Documents').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/hr_letters"]').contains('Manage HR Letters').click()
          cy.location("pathname").should("equal","/en/hr_letters")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Documents').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/hr_letter_templates"]').contains('Templates').click()
          cy.location("pathname").should("equal","/en/hr_letter_templates")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Documents').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/hr_letter_types"]').contains('Categories').click()
          cy.location("pathname").should("equal","/en/hr_letter_types")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Documents').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/hr_letter_types"]').contains('Categories').click()
          cy.location("pathname").should("equal","/en/hr_letter_types")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Requests').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/timeoff_transaction/requests/new"]').contains('Request Time Off').click()
          cy.location("pathname").should("equal","/en/timeoff_transaction/requests/new")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Requests').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/overtime/requests/new"]').contains('Request Overtime').click()
          cy.location("pathname").should("equal","/en/overtime/requests/new")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Requests').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/airticket_transaction/requests/new"]').contains('Request Air Ticket Transaction').click()
          cy.location("pathname").should("equal","/en/airticket_transaction/requests/new")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Requests').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/airticket_transaction/miscellaneous_request/requests"]').contains('My Miscellaneous Requests').click()
          cy.location("pathname").should("equal","/en/miscellaneous_request/requests")
        })
        cy.openSideMenu().click()
        cy.pathDataTest('Requests').click()
        cy.get('[class="nano"] > ul').children().then(() => {
          cy.get('a[href*="/en/airticket_transaction/miscellaneous_requests"]').contains('Manage Miscellaneous Requests').click()
          cy.location("pathname").should("equal","/en/miscellaneous_requests")
        })
        })
    
})